/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CantinaRecord {
  'memberId' : Principal,
  'paymentStatus' : PaymentStatus,
  'date' : bigint,
  'item' : string,
  'pixQrCode' : string,
  'amount' : number,
}
export type Cargo = { 'membro' : null } |
  { 'admin' : null } |
  { 'congregado' : null };
export interface Escala {
  'ministerio' : string,
  'volunteerName' : string,
  'date' : bigint,
  'volunteerId' : Principal,
  'confirmed' : boolean,
}
export interface Event {
  'title' : string,
  'description' : string,
  'posterImage' : [] | [ExternalBlob],
  'eventDate' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Member {
  'id' : Principal,
  'status' : MemberStatus,
  'todaysBirthday' : boolean,
  'entryDate' : [] | [bigint],
  'birthDate' : [] | [bigint],
  'cargo' : Cargo,
  'lgpd' : boolean,
  'name' : string,
  'phone' : string,
  'photo' : [] | [ExternalBlob],
}
export type MemberStatus = { 'active' : null } |
  { 'pending' : null };
export type PaymentStatus = { 'owing' : null } |
  { 'paid' : null };
export interface Prayer {
  'request' : string,
  'createdAt' : bigint,
  'memberName' : string,
  'visibility' : PrayerVisibility,
}
export type PrayerVisibility = { 'publicPrayer' : null } |
  { 'pastorOnly' : null };
export interface Project {
  'name' : string,
  'progressPhoto' : [] | [ExternalBlob],
  'targetAmount' : number,
  'currentAmount' : number,
}
export interface Tithe {
  'status' : TitheStatus,
  'memberId' : Principal,
  'receiptImage' : [] | [ExternalBlob],
  'date' : bigint,
  'amount' : number,
}
export type TitheStatus = { 'pending' : null } |
  { 'confirmed' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCantina' : ActorMethod<[CantinaRecord], undefined>,
  'addEvent' : ActorMethod<[Event], undefined>,
  'addOrUpdateCantinaRecord' : ActorMethod<[string, CantinaRecord], undefined>,
  'addOrUpdateTithe' : ActorMethod<[string, Tithe], undefined>,
  'addPrayer' : ActorMethod<[Prayer], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addTithe' : ActorMethod<[string, Tithe], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmTithe' : ActorMethod<[string], undefined>,
  'contributionProject' : ActorMethod<[string, number], number>,
  'deleteTithe' : ActorMethod<[string], undefined>,
  'editScale' : ActorMethod<[Escala], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllOverdueCantinaRecords' : ActorMethod<[], Array<CantinaRecord>>,
  'getAllTithesByAdmin' : ActorMethod<[], Array<Tithe>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCantinaOwingRecordsForMember' : ActorMethod<
    [Principal],
    Array<CantinaRecord>
  >,
  'getCantinaRecordById' : ActorMethod<[string], [] | [CantinaRecord]>,
  'getEventByTitle' : ActorMethod<[string], [] | [Event]>,
  'getMember' : ActorMethod<[Principal], [] | [Member]>,
  'getMemberScales' : ActorMethod<[Principal], Array<Escala>>,
  'getMembersWithOldTithes' : ActorMethod<[], Array<Principal>>,
  'getOwnCantinaRecords' : ActorMethod<[], Array<CantinaRecord>>,
  'getOwnTithes' : ActorMethod<[], Array<Tithe>>,
  'getPrayersByVisibility' : ActorMethod<[PrayerVisibility], Array<Prayer>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getTitheById' : ActorMethod<[string], [] | [Tithe]>,
  'getTodaysBirthdays' : ActorMethod<[], Array<Member>>,
  'getUpcomingBirthdays' : ActorMethod<[], Array<[Member, bigint]>>,
  'getUserPrayers' : ActorMethod<[string], Array<Prayer>>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'selfInitializeAsFirstAdmin' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markRecordPaid' : ActorMethod<[string], undefined>,
  'removeEvent' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateTithe' : ActorMethod<[string, number], undefined>,
  'upsertMember' : ActorMethod<[Member], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];