/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PaymentStatus = IDL.Variant({
  'owing' : IDL.Null,
  'paid' : IDL.Null,
});
export const CantinaRecord = IDL.Record({
  'memberId' : IDL.Principal,
  'paymentStatus' : PaymentStatus,
  'date' : IDL.Int,
  'item' : IDL.Text,
  'pixQrCode' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Event = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'posterImage' : IDL.Opt(ExternalBlob),
  'eventDate' : IDL.Int,
});
export const TitheStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const TitheType = IDL.Variant({
  'tithe' : IDL.Null,
  'offering' : IDL.Null,
});
export const Tithe = IDL.Record({
  'status' : TitheStatus,
  'memberId' : IDL.Principal,
  'receiptImage' : IDL.Opt(ExternalBlob),
  'date' : IDL.Int,
  'amount' : IDL.Float64,
  'titheType' : TitheType,
});
export const PrayerVisibility = IDL.Variant({
  'publicPrayer' : IDL.Null,
  'pastorOnly' : IDL.Null,
});
export const Prayer = IDL.Record({
  'request' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberName' : IDL.Text,
  'visibility' : PrayerVisibility,
});
export const Project = IDL.Record({
  'name' : IDL.Text,
  'progressPhoto' : IDL.Opt(ExternalBlob),
  'pixKey' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'currentAmount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Escala = IDL.Record({
  'ministerio' : IDL.Text,
  'volunteerName' : IDL.Text,
  'date' : IDL.Int,
  'volunteerId' : IDL.Principal,
  'confirmed' : IDL.Bool,
});
export const MemberStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const Cargo = IDL.Variant({
  'membro' : IDL.Null,
  'admin' : IDL.Null,
  'congregado' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Principal,
  'status' : MemberStatus,
  'todaysBirthday' : IDL.Bool,
  'entryDate' : IDL.Opt(IDL.Int),
  'birthDate' : IDL.Opt(IDL.Int),
  'cargo' : Cargo,
  'lgpd' : IDL.Bool,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCantina' : IDL.Func([CantinaRecord], [], []),
  'addEvent' : IDL.Func([Event], [], []),
  'addOrUpdateCantinaRecord' : IDL.Func([IDL.Text, CantinaRecord], [], []),
  'addOrUpdateTithe' : IDL.Func([IDL.Text, Tithe], [], []),
  'addPrayer' : IDL.Func([Prayer], [], []),
  'addProject' : IDL.Func([Project], [], []),
  'addTithe' : IDL.Func([IDL.Text, Tithe], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmTithe' : IDL.Func([IDL.Text], [], []),
  'contributionProject' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'deleteTithe' : IDL.Func([IDL.Text], [], []),
  'editScale' : IDL.Func([Escala], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllOverdueCantinaRecords' : IDL.Func(
      [],
      [IDL.Vec(CantinaRecord)],
      ['query'],
    ),
  'getAllTithesByAdmin' : IDL.Func([], [IDL.Vec(Tithe)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCantinaOwingRecordsForMember' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CantinaRecord)],
      ['query'],
    ),
  'getCantinaRecordById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CantinaRecord)],
      ['query'],
    ),
  'getEventByTitle' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getMember' : IDL.Func([IDL.Principal], [IDL.Opt(Member)], ['query']),
  'getMemberScales' : IDL.Func([IDL.Principal], [IDL.Vec(Escala)], ['query']),
  'getMembersWithOldTithes' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getOwnCantinaRecords' : IDL.Func([], [IDL.Vec(CantinaRecord)], ['query']),
  'getOwnTithes' : IDL.Func([], [IDL.Vec(Tithe)], ['query']),
  'getPrayersByVisibility' : IDL.Func(
      [PrayerVisibility],
      [IDL.Vec(Prayer)],
      ['query'],
    ),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getTitheById' : IDL.Func([IDL.Text], [IDL.Opt(Tithe)], ['query']),
  'getTodaysBirthdays' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getUpcomingBirthdays' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Member, IDL.Int))],
      ['query'],
    ),
  'getUserPrayers' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markRecordPaid' : IDL.Func([IDL.Text], [], []),
  'removeEvent' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'selfInitializeAsFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateTithe' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'upsertMember' : IDL.Func([Member], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PaymentStatus = IDL.Variant({ 'owing' : IDL.Null, 'paid' : IDL.Null });
  const CantinaRecord = IDL.Record({
    'memberId' : IDL.Principal,
    'paymentStatus' : PaymentStatus,
    'date' : IDL.Int,
    'item' : IDL.Text,
    'pixQrCode' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Event = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'posterImage' : IDL.Opt(ExternalBlob),
    'eventDate' : IDL.Int,
  });
  const TitheStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const TitheType = IDL.Variant({ 'tithe' : IDL.Null, 'offering' : IDL.Null });
  const Tithe = IDL.Record({
    'status' : TitheStatus,
    'memberId' : IDL.Principal,
    'receiptImage' : IDL.Opt(ExternalBlob),
    'date' : IDL.Int,
    'amount' : IDL.Float64,
    'titheType' : TitheType,
  });
  const PrayerVisibility = IDL.Variant({
    'publicPrayer' : IDL.Null,
    'pastorOnly' : IDL.Null,
  });
  const Prayer = IDL.Record({
    'request' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberName' : IDL.Text,
    'visibility' : PrayerVisibility,
  });
  const Project = IDL.Record({
    'name' : IDL.Text,
    'progressPhoto' : IDL.Opt(ExternalBlob),
    'pixKey' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'currentAmount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Escala = IDL.Record({
    'ministerio' : IDL.Text,
    'volunteerName' : IDL.Text,
    'date' : IDL.Int,
    'volunteerId' : IDL.Principal,
    'confirmed' : IDL.Bool,
  });
  const MemberStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Cargo = IDL.Variant({
    'membro' : IDL.Null,
    'admin' : IDL.Null,
    'congregado' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Principal,
    'status' : MemberStatus,
    'todaysBirthday' : IDL.Bool,
    'entryDate' : IDL.Opt(IDL.Int),
    'birthDate' : IDL.Opt(IDL.Int),
    'cargo' : Cargo,
    'lgpd' : IDL.Bool,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCantina' : IDL.Func([CantinaRecord], [], []),
    'addEvent' : IDL.Func([Event], [], []),
    'addOrUpdateCantinaRecord' : IDL.Func([IDL.Text, CantinaRecord], [], []),
    'addOrUpdateTithe' : IDL.Func([IDL.Text, Tithe], [], []),
    'addPrayer' : IDL.Func([Prayer], [], []),
    'addProject' : IDL.Func([Project], [], []),
    'addTithe' : IDL.Func([IDL.Text, Tithe], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmTithe' : IDL.Func([IDL.Text], [], []),
    'contributionProject' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'deleteTithe' : IDL.Func([IDL.Text], [], []),
    'editScale' : IDL.Func([Escala], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllOverdueCantinaRecords' : IDL.Func(
        [],
        [IDL.Vec(CantinaRecord)],
        ['query'],
      ),
    'getAllTithesByAdmin' : IDL.Func([], [IDL.Vec(Tithe)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCantinaOwingRecordsForMember' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CantinaRecord)],
        ['query'],
      ),
    'getCantinaRecordById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CantinaRecord)],
        ['query'],
      ),
    'getEventByTitle' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getMember' : IDL.Func([IDL.Principal], [IDL.Opt(Member)], ['query']),
    'getMemberScales' : IDL.Func([IDL.Principal], [IDL.Vec(Escala)], ['query']),
    'getMembersWithOldTithes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getOwnCantinaRecords' : IDL.Func([], [IDL.Vec(CantinaRecord)], ['query']),
    'getOwnTithes' : IDL.Func([], [IDL.Vec(Tithe)], ['query']),
    'getPrayersByVisibility' : IDL.Func(
        [PrayerVisibility],
        [IDL.Vec(Prayer)],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getTitheById' : IDL.Func([IDL.Text], [IDL.Opt(Tithe)], ['query']),
    'getTodaysBirthdays' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getUpcomingBirthdays' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Member, IDL.Int))],
        ['query'],
      ),
    'getUserPrayers' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markRecordPaid' : IDL.Func([IDL.Text], [], []),
    'removeEvent' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'selfInitializeAsFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateTithe' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'upsertMember' : IDL.Func([Member], [], []),
  });
};

export const init = ({ IDL }) => { return []; };