/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Tithe {
    status: TitheStatus;
    memberId: Principal;
    receiptImage?: ExternalBlob;
    date: bigint;
    amount: number;
    titheType: TitheType;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    title: string;
    description: string;
    posterImage?: ExternalBlob;
    eventDate: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CantinaRecord {
    memberId: Principal;
    paymentStatus: PaymentStatus;
    date: bigint;
    item: string;
    pixQrCode: string;
    amount: number;
}
export interface Escala {
    ministerio: string;
    volunteerName: string;
    date: bigint;
    volunteerId: Principal;
    confirmed: boolean;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Prayer {
    request: string;
    createdAt: bigint;
    memberName: string;
    visibility: PrayerVisibility;
}
export interface Member {
    id: Principal;
    status: MemberStatus;
    todaysBirthday: boolean;
    entryDate?: bigint;
    birthDate?: bigint;
    cargo: Cargo;
    lgpd: boolean;
    name: string;
    phone: string;
    photo?: ExternalBlob;
}
export interface Project {
    name: string;
    progressPhoto?: ExternalBlob;
    pixKey: string;
    targetAmount: number;
    currentAmount: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Cargo {
    membro = "membro",
    admin = "admin",
    congregado = "congregado"
}
export enum MemberStatus {
    active = "active",
    pending = "pending"
}
export enum PaymentStatus {
    owing = "owing",
    paid = "paid"
}
export enum PrayerVisibility {
    publicPrayer = "publicPrayer",
    pastorOnly = "pastorOnly"
}
export enum TitheStatus {
    pending = "pending",
    confirmed = "confirmed"
}
export enum TitheType {
    tithe = "tithe",
    offering = "offering"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCantina(record: CantinaRecord): Promise<void>;
    addEvent(event: Event): Promise<void>;
    addOrUpdateCantinaRecord(recordId: string, record: CantinaRecord): Promise<void>;
    addOrUpdateTithe(recordId: string, record: Tithe): Promise<void>;
    addPrayer(prayer: Prayer): Promise<void>;
    addProject(project: Project): Promise<void>;
    addTithe(titheId: string, tithe: Tithe): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmTithe(recordId: string): Promise<void>;
    contributionProject(projectName: string, contribution: number): Promise<number>;
    deleteProject(projectName: string): Promise<void>;
    deleteTithe(titheId: string): Promise<void>;
    editScale(jornada: Escala): Promise<void>;
    getAllEvents(): Promise<Array<Event>>;
    getAllMembers(): Promise<Array<Member>>;
    getAllOverdueCantinaRecords(): Promise<Array<CantinaRecord>>;
    getAllTithesByAdmin(): Promise<Array<Tithe>>;
    getCallerUserRole(): Promise<UserRole>;
    getCantinaOwingRecordsForMember(memberId: Principal): Promise<Array<CantinaRecord>>;
    getCantinaRecordById(recordId: string): Promise<CantinaRecord | null>;
    getEventByTitle(title: string): Promise<Event | null>;
    getMember(id: Principal): Promise<Member | null>;
    getMemberScales(memberId: Principal): Promise<Array<Escala>>;
    getMembersWithOldTithes(): Promise<Array<Principal>>;
    getOwnCantinaRecords(): Promise<Array<CantinaRecord>>;
    getOwnTithes(): Promise<Array<Tithe>>;
    getPrayersByVisibility(visibility: PrayerVisibility): Promise<Array<Prayer>>;
    getProjects(): Promise<Array<Project>>;
    getTitheById(id: string): Promise<Tithe | null>;
    getTodaysBirthdays(): Promise<Array<Member>>;
    getUpcomingBirthdays(): Promise<Array<[Member, bigint]>>;
    getUserPrayers(name: string): Promise<Array<Prayer>>;
    isAdminAssigned(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markRecordPaid(recordId: string): Promise<void>;
    removeEvent(title: string): Promise<void>;
    requestApproval(): Promise<void>;
    selfInitializeAsFirstAdmin(): Promise<boolean>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateTithe(titheId: string, amount: number): Promise<void>;
    upsertMember(member: Member): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, CantinaRecord as _CantinaRecord, Cargo as _Cargo, Event as _Event, ExternalBlob as _ExternalBlob, Member as _Member, MemberStatus as _MemberStatus, PaymentStatus as _PaymentStatus, Prayer as _Prayer, PrayerVisibility as _PrayerVisibility, Project as _Project, Tithe as _Tithe, TitheStatus as _TitheStatus, TitheType as _TitheType, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCantina(arg0: CantinaRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCantina(to_candid_CantinaRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCantina(to_candid_CantinaRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(await to_candid_Event_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(await to_candid_Event_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateCantinaRecord(arg0: string, arg1: CantinaRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCantinaRecord(arg0, to_candid_CantinaRecord_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCantinaRecord(arg0, to_candid_CantinaRecord_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addOrUpdateTithe(arg0: string, arg1: Tithe): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTithe(arg0, await to_candid_Tithe_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTithe(arg0, await to_candid_Tithe_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPrayer(arg0: Prayer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPrayer(to_candid_Prayer_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPrayer(to_candid_Prayer_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(await to_candid_Project_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(await to_candid_Project_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTithe(arg0: string, arg1: Tithe): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTithe(arg0, await to_candid_Tithe_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTithe(arg0, await to_candid_Tithe_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmTithe(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmTithe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmTithe(arg0);
            return result;
        }
    }
    async contributionProject(arg0: string, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.contributionProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.contributionProject(arg0, arg1);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTithe(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTithe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTithe(arg0);
            return result;
        }
    }
    async editScale(arg0: Escala): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editScale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editScale(arg0);
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOverdueCantinaRecords(): Promise<Array<CantinaRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOverdueCantinaRecords();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOverdueCantinaRecords();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTithesByAdmin(): Promise<Array<Tithe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTithesByAdmin();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTithesByAdmin();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCantinaOwingRecordsForMember(arg0: Principal): Promise<Array<CantinaRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCantinaOwingRecordsForMember(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCantinaOwingRecordsForMember(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCantinaRecordById(arg0: string): Promise<CantinaRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCantinaRecordById(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCantinaRecordById(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventByTitle(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventByTitle(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventByTitle(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: Principal): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberScales(arg0: Principal): Promise<Array<Escala>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberScales(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberScales(arg0);
            return result;
        }
    }
    async getMembersWithOldTithes(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembersWithOldTithes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembersWithOldTithes();
            return result;
        }
    }
    async getOwnCantinaRecords(): Promise<Array<CantinaRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnCantinaRecords();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnCantinaRecords();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnTithes(): Promise<Array<Tithe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnTithes();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnTithes();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrayersByVisibility(arg0: PrayerVisibility): Promise<Array<Prayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrayersByVisibility(to_candid_PrayerVisibility_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrayersByVisibility(to_candid_PrayerVisibility_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTitheById(arg0: string): Promise<Tithe | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTitheById(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTitheById(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysBirthdays(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysBirthdays();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysBirthdays();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingBirthdays(): Promise<Array<[Member, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingBirthdays();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingBirthdays();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPrayers(arg0: string): Promise<Array<Prayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPrayers(arg0);
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPrayers(arg0);
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminAssigned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminAssigned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminAssigned();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async markRecordPaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markRecordPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRecordPaid(arg0);
            return result;
        }
    }
    async removeEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEvent(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async selfInitializeAsFirstAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.selfInitializeAsFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfInitializeAsFirstAdmin();
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n75(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n75(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTithe(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTithe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTithe(arg0, arg1);
            return result;
        }
    }
    async upsertMember(arg0: Member): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMember(await to_candid_Member_n77(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMember(await to_candid_Member_n77(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function from_candid_CantinaRecord_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CantinaRecord): CantinaRecord {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Cargo_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cargo): Cargo {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_Event_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MemberStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberStatus): MemberStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Member_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Promise<Member> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PrayerVisibility_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrayerVisibility): PrayerVisibility {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Prayer_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prayer): Prayer {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
async function from_candid_Project_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Promise<Project> {
    return await from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_TitheStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TitheStatus): TitheStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TitheType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TitheType): TitheType {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_Tithe_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tithe): Promise<Tithe> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CantinaRecord]): CantinaRecord | null {
    return value.length === 0 ? null : from_candid_CantinaRecord_n43(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Promise<Event | null> {
    return value.length === 0 ? null : await from_candid_Event_n30(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Promise<Member | null> {
    return value.length === 0 ? null : await from_candid_Member_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tithe]): Promise<Tithe | null> {
    return value.length === 0 ? null : await from_candid_Tithe_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    posterImage: [] | [_ExternalBlob];
    eventDate: bigint;
}): Promise<{
    title: string;
    description: string;
    posterImage?: ExternalBlob;
    eventDate: bigint;
}> {
    return {
        title: value.title,
        description: value.description,
        posterImage: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.posterImage)),
        eventDate: value.eventDate
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: _MemberStatus;
    todaysBirthday: boolean;
    entryDate: [] | [bigint];
    birthDate: [] | [bigint];
    cargo: _Cargo;
    lgpd: boolean;
    name: string;
    phone: string;
    photo: [] | [_ExternalBlob];
}): Promise<{
    id: Principal;
    status: MemberStatus;
    todaysBirthday: boolean;
    entryDate?: bigint;
    birthDate?: bigint;
    cargo: Cargo;
    lgpd: boolean;
    name: string;
    phone: string;
    photo?: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_MemberStatus_n37(_uploadFile, _downloadFile, value.status),
        todaysBirthday: value.todaysBirthday,
        entryDate: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.entryDate)),
        birthDate: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.birthDate)),
        cargo: from_candid_Cargo_n40(_uploadFile, _downloadFile, value.cargo),
        lgpd: value.lgpd,
        name: value.name,
        phone: value.phone,
        photo: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: Principal;
    paymentStatus: _PaymentStatus;
    date: bigint;
    item: string;
    pixQrCode: string;
    amount: number;
}): {
    memberId: Principal;
    paymentStatus: PaymentStatus;
    date: bigint;
    item: string;
    pixQrCode: string;
    amount: number;
} {
    return {
        memberId: value.memberId,
        paymentStatus: from_candid_PaymentStatus_n45(_uploadFile, _downloadFile, value.paymentStatus),
        date: value.date,
        item: value.item,
        pixQrCode: value.pixQrCode,
        amount: value.amount
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TitheStatus;
    memberId: Principal;
    receiptImage: [] | [_ExternalBlob];
    date: bigint;
    amount: number;
    titheType: _TitheType;
}): Promise<{
    status: TitheStatus;
    memberId: Principal;
    receiptImage?: ExternalBlob;
    date: bigint;
    amount: number;
    titheType: TitheType;
}> {
    return {
        status: from_candid_TitheStatus_n50(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        receiptImage: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.receiptImage)),
        date: value.date,
        amount: value.amount,
        titheType: from_candid_TitheType_n52(_uploadFile, _downloadFile, value.titheType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    request: string;
    createdAt: bigint;
    memberName: string;
    visibility: _PrayerVisibility;
}): {
    request: string;
    createdAt: bigint;
    memberName: string;
    visibility: PrayerVisibility;
} {
    return {
        request: value.request,
        createdAt: value.createdAt,
        memberName: value.memberName,
        visibility: from_candid_PrayerVisibility_n62(_uploadFile, _downloadFile, value.visibility)
    };
}
async function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    progressPhoto: [] | [_ExternalBlob];
    pixKey: string;
    targetAmount: number;
    currentAmount: number;
}): Promise<{
    name: string;
    progressPhoto?: ExternalBlob;
    pixKey: string;
    targetAmount: number;
    currentAmount: number;
}> {
    return {
        name: value.name,
        progressPhoto: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.progressPhoto)),
        pixKey: value.pixKey,
        targetAmount: value.targetAmount,
        currentAmount: value.currentAmount
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n73(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
async function from_candid_tuple_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Member, bigint]): Promise<[Member, bigint]> {
    return [
        await from_candid_Member_n35(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
}): MemberStatus {
    return "active" in value ? MemberStatus.active : "pending" in value ? MemberStatus.pending : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    membro: null;
} | {
    admin: null;
} | {
    congregado: null;
}): Cargo {
    return "membro" in value ? Cargo.membro : "admin" in value ? Cargo.admin : "congregado" in value ? Cargo.congregado : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owing: null;
} | {
    paid: null;
}): PaymentStatus {
    return "owing" in value ? PaymentStatus.owing : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
}): TitheStatus {
    return "pending" in value ? TitheStatus.pending : "confirmed" in value ? TitheStatus.confirmed : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tithe: null;
} | {
    offering: null;
}): TitheType {
    return "tithe" in value ? TitheType.tithe : "offering" in value ? TitheType.offering : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicPrayer: null;
} | {
    pastorOnly: null;
}): PrayerVisibility {
    return "publicPrayer" in value ? PrayerVisibility.publicPrayer : "pastorOnly" in value ? PrayerVisibility.pastorOnly : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Promise<Array<Member>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Member_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CantinaRecord>): Array<CantinaRecord> {
    return value.map((x)=>from_candid_CantinaRecord_n43(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tithe>): Promise<Array<Tithe>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Tithe_n48(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prayer>): Array<Prayer> {
    return value.map((x)=>from_candid_Prayer_n60(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Promise<Array<Project>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Project_n65(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Member, bigint]>): Promise<Array<[Member, bigint]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n69(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n71(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_CantinaRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CantinaRecord): _CantinaRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Cargo_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cargo): _Cargo {
    return to_candid_variant_n82(_uploadFile, _downloadFile, value);
}
async function to_candid_Event_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): Promise<_Event> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MemberStatus_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): _MemberStatus {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
async function to_candid_Member_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Member): Promise<_Member> {
    return await to_candid_record_n78(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PrayerVisibility_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrayerVisibility): _PrayerVisibility {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Prayer_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Prayer): _Prayer {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_Project_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): Promise<_Project> {
    return await to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_TitheStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TitheStatus): _TitheStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TitheType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TitheType): _TitheType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_Tithe_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tithe): Promise<_Tithe> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    posterImage?: ExternalBlob;
    eventDate: bigint;
}): Promise<{
    title: string;
    description: string;
    posterImage: [] | [_ExternalBlob];
    eventDate: bigint;
}> {
    return {
        title: value.title,
        description: value.description,
        posterImage: value.posterImage ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.posterImage)) : candid_none(),
        eventDate: value.eventDate
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TitheStatus;
    memberId: Principal;
    receiptImage?: ExternalBlob;
    date: bigint;
    amount: number;
    titheType: TitheType;
}): Promise<{
    status: _TitheStatus;
    memberId: Principal;
    receiptImage: [] | [_ExternalBlob];
    date: bigint;
    amount: number;
    titheType: _TitheType;
}> {
    return {
        status: to_candid_TitheStatus_n17(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        receiptImage: value.receiptImage ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.receiptImage)) : candid_none(),
        date: value.date,
        amount: value.amount,
        titheType: to_candid_TitheType_n19(_uploadFile, _downloadFile, value.titheType)
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    request: string;
    createdAt: bigint;
    memberName: string;
    visibility: PrayerVisibility;
}): {
    request: string;
    createdAt: bigint;
    memberName: string;
    visibility: _PrayerVisibility;
} {
    return {
        request: value.request,
        createdAt: value.createdAt,
        memberName: value.memberName,
        visibility: to_candid_PrayerVisibility_n23(_uploadFile, _downloadFile, value.visibility)
    };
}
async function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    progressPhoto?: ExternalBlob;
    pixKey: string;
    targetAmount: number;
    currentAmount: number;
}): Promise<{
    name: string;
    progressPhoto: [] | [_ExternalBlob];
    pixKey: string;
    targetAmount: number;
    currentAmount: number;
}> {
    return {
        name: value.name,
        progressPhoto: value.progressPhoto ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.progressPhoto)) : candid_none(),
        pixKey: value.pixKey,
        targetAmount: value.targetAmount,
        currentAmount: value.currentAmount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: MemberStatus;
    todaysBirthday: boolean;
    entryDate?: bigint;
    birthDate?: bigint;
    cargo: Cargo;
    lgpd: boolean;
    name: string;
    phone: string;
    photo?: ExternalBlob;
}): Promise<{
    id: Principal;
    status: _MemberStatus;
    todaysBirthday: boolean;
    entryDate: [] | [bigint];
    birthDate: [] | [bigint];
    cargo: _Cargo;
    lgpd: boolean;
    name: string;
    phone: string;
    photo: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        status: to_candid_MemberStatus_n79(_uploadFile, _downloadFile, value.status),
        todaysBirthday: value.todaysBirthday,
        entryDate: value.entryDate ? candid_some(value.entryDate) : candid_none(),
        birthDate: value.birthDate ? candid_some(value.birthDate) : candid_none(),
        cargo: to_candid_Cargo_n81(_uploadFile, _downloadFile, value.cargo),
        lgpd: value.lgpd,
        name: value.name,
        phone: value.phone,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.photo)) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: Principal;
    paymentStatus: PaymentStatus;
    date: bigint;
    item: string;
    pixQrCode: string;
    amount: number;
}): {
    memberId: Principal;
    paymentStatus: _PaymentStatus;
    date: bigint;
    item: string;
    pixQrCode: string;
    amount: number;
} {
    return {
        memberId: value.memberId,
        paymentStatus: to_candid_PaymentStatus_n10(_uploadFile, _downloadFile, value.paymentStatus),
        date: value.date,
        item: value.item,
        pixQrCode: value.pixQrCode,
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    owing: null;
} | {
    paid: null;
} {
    return value == PaymentStatus.owing ? {
        owing: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TitheStatus): {
    pending: null;
} | {
    confirmed: null;
} {
    return value == TitheStatus.pending ? {
        pending: null
    } : value == TitheStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TitheType): {
    tithe: null;
} | {
    offering: null;
} {
    return value == TitheType.tithe ? {
        tithe: null
    } : value == TitheType.offering ? {
        offering: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrayerVisibility): {
    publicPrayer: null;
} | {
    pastorOnly: null;
} {
    return value == PrayerVisibility.publicPrayer ? {
        publicPrayer: null
    } : value == PrayerVisibility.pastorOnly ? {
        pastorOnly: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): {
    active: null;
} | {
    pending: null;
} {
    return value == MemberStatus.active ? {
        active: null
    } : value == MemberStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cargo): {
    membro: null;
} | {
    admin: null;
} | {
    congregado: null;
} {
    return value == Cargo.membro ? {
        membro: null
    } : value == Cargo.admin ? {
        admin: null
    } : value == Cargo.congregado ? {
        congregado: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
